
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../back/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3306:3306"
    restart: always

  backend:
    build:
      context: ../back
      dockerfile: Dockerfile
    environment:
      JDBC_DRIVER: ${JDBC_DRIVER}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USER: ${DATASOURCE_USER}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  db_data:
