version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 9
      MYSQL_DATABASE: teachua
      MYSQL_USER: root
      MYSQL_PASSWORD: 9
    volumes:
      - db_data:/var/lib/mysql
      - ./back/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3306:3306"
    restart: always

  backend:
    build:
      context: ../back
      dockerfile: Dockerfile
    environment:
      JDBC_DRIVER: org.mariadb.jdbc.Driver
      DATASOURCE_URL: jdbc:mariadb://db:3306/teachua
      DATASOURCE_USER: root
      DATASOURCE_PASSWORD: 9
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  db_data:
