apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teachua
  namespace: argocd
spec:
  description: "Проект для управління додатком TeachUA"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

